### ISSUE TITLE
TypeError: Cannot read property 'contractName' of undefined

### ISSUE THREAD

**Issue by schmijos** [okwme/dapp-scratch#6]
![image](https://user-images.githubusercontent.com/245443/36204095-2e0283ee-118a-11e8-90e2-73af5afcd50b.png)

Because `contractName` is statically set to `sampleContract` [here](https://github.com/okwme/dapp-scratch/blob/5e214264aeb8d6996346b718748c846fd2dae02b/lib/dapp-scratch.js#L18), the file (inferred with `contractNameCapitalized`) doesn't exist.

**Comment by okwme** [comment]
must have been a bad merge to the current version as this is obv a breaking issue.
thank you for pointing it out @schmijos !
